version: '3.8'

services:
  web:
    build: .
    image: ipcal_web:latest
    ports:
      - "5000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - GUNICORN_WORKERS=4
    command: gunicorn --workers "$GUNICORN_WORKERS" --bind "0.0.0.0:8000" app:app